src/ipa.c File Reference
#include <stdint.h>
*
#include <errno.h>
*
#include <unistd.h>
*
#include <string.h>
*
#include <osmocom/core/utils.h>
*
#include <osmocom/core/linuxlist.h>
*
#include <osmocom/core/write_queue.h>
*
#include <osmocom/core/logging.h>
*
#include <osmocom/core/timer.h>
*
#include <osmocom/core/socket.h>
*
#include <osmocom/core/byteswap.h>
*
#include <osmocom/gsm/ipa.h>
*
#include <osmocom/gsm/protocol/ipaccess.h>
*
#include <osmocom/netif/ipa.h>
*
#include <osmocom/sigtran/xua_msg.h>
*
#include <osmocom/sigtran/mtp_sap.h>
*
#include <osmocom/sigtran/sccp_sap.h>
*
#include <osmocom/sigtran/osmo_ss7.h>
*
#include <osmocom/sigtran/protocol/m3ua.h>
*
#include <osmocom/sigtran/protocol/sua.h>
*
#include <osmocom/sigtran/protocol/mtp.h>
*
#include `xua_internal.h`
*
#include `xua_asp_fsm.h`
*
Functions
int ipa_tx_xua_as (struct osmo_ss7_as *as, struct xua_msg *xua)
Send a given xUA message via a given IPA `Application Server`.
static int ipa_rx_msg_ccm (struct osmo_ss7_asp *asp, struct msgb *msg)
static struct osmo_ss7_as * find_as_for_asp (struct osmo_ss7_asp *asp)
static struct msgb * patch_sccp_with_pc (struct osmo_ss7_asp *asp, struct msgb *sccp_msg_in, uint32_t opc, uint32_t dpc)
static int ipa_rx_msg_sccp (struct osmo_ss7_asp *asp, struct msgb *msg)
int ipa_rx_msg (struct osmo_ss7_asp *asp, struct msgb *msg)
process M3UA message received from socket
Function Documentation
static struct osmo_ss7_as* find_as_for_asp (struct osmo_ss7_asp * asp) [static]
References osmo_ss7_instance::as_list, osmo_ss7_asp::inst, osmo_ss7_as::list, and osmo_ss7_as_has_asp().
Referenced by ipa_rx_msg_sccp().
int ipa_rx_msg (struct osmo_ss7_asp * asp, struct msgb * msg)
process M3UA message received from socket
Parameters
in asp Application Server Process receiving msg
in msg received message buffer. Callee takes ownership!
Returns
0 on success; negative on error
References osmo_ss7_asp::cfg, ipa_rx_msg_ccm(), ipa_rx_msg_sccp(), OSMO_SS7_ASP_PROT_IPA, osmo_ss7_asp::proto, and ss7_asp_rx_unknown().
Referenced by ipa_cli_read_cb(), and ipa_srv_conn_cb().
static int ipa_rx_msg_ccm (struct osmo_ss7_asp * asp, struct msgb * msg) [static]
References osmo_ss7_asp::fi, IPA_ASP_E_ID_ACK, IPA_ASP_E_ID_GET, IPA_ASP_E_ID_RESP, LOGPASP, msg_type, XUA_ASP_E_ASPSM_BEAT, and XUA_ASP_E_ASPSM_BEAT_ACK.
Referenced by ipa_rx_msg().
static int ipa_rx_msg_sccp (struct osmo_ss7_asp * asp, struct msgb * msg) [static]
References osmo_ss7_as::cfg, osmo_ss7_asp::cfg, m3ua_data_hdr::dpc, dpc, find_as_for_asp(), osmo_ss7_asp::inst, osmo_ss7_asp::is_server, LOGPASP, m3ua_dh_to_xfer_param(), m3ua_hmdc_rx_from_l2(), m3ua_xfer_from_data(), xua_msg::mtp, MTP_SI_SCCP, m3ua_data_hdr::opc, opc, patch_sccp_with_pc(), osmo_ss7_routing_key::pc, osmo_ss7_as::pc_override, osmo_ss7_as::routing_key, m3ua_data_hdr::si, and xua_msg_free().
Referenced by ipa_rx_msg().
int ipa_tx_xua_as (struct osmo_ss7_as * as, struct xua_msg * xua)
Send a given xUA message via a given IPA `Application Server`.
Parameters
in as Application Server through which to send xua
in xua xUA message to be sent
Returns
0 on success; negative on error
References osmo_ss7_as::cfg, xua_msg_part::dat, xua_msg_part::len, M3UA_IEI_PROT_DATA, OSMO_SS7_ASP_PROT_IPA, osmo_ss7_as::proto, xua_as_transmit_msg(), and xua_msg_find_tag().
Referenced by hmrt_message_for_routing().
static struct msgb* patch_sccp_with_pc (struct osmo_ss7_asp * asp, struct msgb * sccp_msg_in, uint32_t opc, uint32_t dpc) [static]
References dpc, LOGPASP, opc, OSMO_SCCP_ADDR_T_PC, osmo_sccp_to_xua(), osmo_sua_to_sccp(), osmo_sccp_addr::pc, osmo_sccp_addr::presence, sua_addr_parse(), SUA_IEI_DEST_ADDR, SUA_IEI_SRC_ADDR, xua_msg_add_sccp_addr(), xua_msg_free(), and xua_msg_free_tag().
Referenced by ipa_rx_msg_sccp().