src/m3ua.c File Reference
#include <stdint.h>
*
#include <errno.h>
*
#include <unistd.h>
*
#include <string.h>
*
#include <osmocom/core/utils.h>
*
#include <osmocom/core/linuxlist.h>
*
#include <osmocom/core/write_queue.h>
*
#include <osmocom/core/logging.h>
*
#include <osmocom/core/timer.h>
*
#include <osmocom/core/socket.h>
*
#include <osmocom/netif/stream.h>
*
#include <osmocom/sigtran/xua_msg.h>
*
#include <osmocom/sigtran/mtp_sap.h>
*
#include <osmocom/sigtran/sccp_sap.h>
*
#include <osmocom/sigtran/osmo_ss7.h>
*
#include <osmocom/sigtran/protocol/m3ua.h>
*
#include <osmocom/sigtran/protocol/sua.h>
*
#include `xua_as_fsm.h`
*
#include `xua_asp_fsm.h`
*
#include `xua_internal.h`
*
Macros
#define M3UA_MSGB_SIZE 1500
#define MAND_IES(msgt, ies) [msgt] = (ies)
#define M3UA_MSG_SIZE 2048
#define M3UA_MSG_HEADROOM 512
Functions
void mtp_xfer_param_to_m3ua_dh (struct m3ua_data_hdr *mdh, const struct osmo_mtp_transfer_param *param)
void m3ua_dh_to_xfer_param (struct osmo_mtp_transfer_param *param, const struct m3ua_data_hdr *mdh)
struct msgb * m3ua_msgb_alloc (const char *name)
struct xua_msg * m3ua_xfer_from_data (const struct m3ua_data_hdr *data_hdr, const uint8_t *data, unsigned int data_len)
static struct xua_msg * m3ua_gen_error (uint32_t err_code)
static struct xua_msg * m3ua_gen_error_msg (uint32_t err_code, struct msgb *msg)
struct xua_msg * m3ua_encode_notify (const struct osmo_xlm_prim_notify *npar)
int m3ua_decode_notify (struct osmo_xlm_prim_notify *npar, void *ctx, const struct xua_msg *xua)
static struct msgb * m3ua_to_msg (struct xua_msg *xua)
static int m3ua_tx_xua_asp (struct osmo_ss7_asp *asp, struct xua_msg *xua)
int m3ua_tx_xua_as (struct osmo_ss7_as *as, struct xua_msg *xua)
Send a given xUA message via a given M3UA Application Server.
struct m3ua_data_hdr * data_hdr_from_m3ua (struct xua_msg *xua)
static int m3ua_rx_xfer (struct osmo_ss7_asp *asp, struct xua_msg *xua)
static int m3ua_rx_mgmt_err (struct osmo_ss7_asp *asp, struct xua_msg *xua)
static int m3ua_rx_mgmt_ntfy (struct osmo_ss7_asp *asp, struct xua_msg *xua)
static int m3ua_rx_mgmt (struct osmo_ss7_asp *asp, struct xua_msg *xua)
static int m3ua_rx_asp (struct osmo_ss7_asp *asp, struct xua_msg *xua)
int m3ua_rx_msg (struct osmo_ss7_asp *asp, struct msgb *msg)
process M3UA message received from socket
Variables
const struct value_string m3ua_err_names []
const struct value_string m3ua_ntfy_type_names []
const struct value_string m3ua_ntfy_stchg_names []
const struct value_string m3ua_ntfy_other_names []
static const struct value_string m3ua_iei_names []
static const uint16_t data_mand_ies []
static const struct value_string m3ua_xfer_msgt_names []
static const struct xua_msg_class msg_class_xfer
static const uint16_t duna_mand_ies []
static const uint16_t dava_mand_ies []
static const uint16_t daud_mand_ies []
static const uint16_t scon_mand_ies []
static const uint16_t dupu_mand_ies []
static const uint16_t drst_mand_ies []
static const struct value_string m3ua_snm_msgt_names []
const struct xua_msg_class m3ua_msg_class_snm
static const struct value_string m3ua_aspsm_msgt_names []
const struct xua_msg_class m3ua_msg_class_aspsm
const struct value_string m3ua_asptm_msgt_names []
const struct xua_msg_class m3ua_msg_class_asptm
static const uint16_t err_req_ies []
static const uint16_t ntfy_req_ies []
static const struct value_string m3ua_mgmt_msgt_names []
const struct xua_msg_class m3ua_msg_class_mgmt
static const uint16_t reg_req_ies []
static const uint16_t reg_rsp_ies []
static const uint16_t dereg_req_ies []
static const uint16_t dereg_rsp_ies []
static const struct value_string m3ua_rkm_msgt_names []
const struct xua_msg_class m3ua_msg_class_rkm
const struct xua_dialect xua_dialect_m3ua
static const struct xua_msg_event_map m3ua_aspxm_map []
Macro Definition Documentation
#define M3UA_MSG_HEADROOM 512
Referenced by m3ua_msgb_alloc().
#define M3UA_MSG_SIZE 2048
Referenced by m3ua_msgb_alloc().
#define M3UA_MSGB_SIZE 1500
#define MAND_IES(msgt, ies) [msgt] = (ies)
Function Documentation
struct m3ua_data_hdr* data_hdr_from_m3ua (struct xua_msg * xua)
References xua_msg_part::dat, xua_msg::hdr, M3UA_IEI_PROT_DATA, M3UA_MSGC_XFER, M3UA_XFER_DATA, xua_common_hdr::msg_class, xua_common_hdr::msg_type, and xua_msg_find_tag().
Referenced by hmdt_message_for_distribution(), and m3ua_rx_xfer().
int m3ua_decode_notify (struct osmo_xlm_prim_notify * npar, void * ctx, const struct xua_msg * xua)
References osmo_xlm_prim_notify::asp_id, xua_msg_part::dat, osmo_xlm_prim_notify::info_string, xua_msg_part::len, M3UA_IEI_ASP_ID, M3UA_IEI_INFO_STRING, M3UA_IEI_ROUTE_CTX, M3UA_IEI_STATUS, NOTIFY_PAR_P_ASP_ID, NOTIFY_PAR_P_ROUTE_CTX, osmo_xlm_prim_notify::presence, osmo_xlm_prim_notify::route_ctx, osmo_xlm_prim_notify::status_info, osmo_xlm_prim_notify::status_type, xua_msg_find_tag(), and xua_msg_part_get_u32().
Referenced by m3ua_rx_mgmt_ntfy(), and sua_rx_mgmt_ntfy().
void m3ua_dh_to_xfer_param (struct osmo_mtp_transfer_param * param, const struct m3ua_data_hdr * mdh)
References osmo_mtp_transfer_param::dpc, m3ua_data_hdr::dpc, m3ua_data_hdr::mp, m3ua_data_hdr::ni, osmo_mtp_transfer_param::opc, m3ua_data_hdr::opc, m3ua_data_hdr::si, osmo_mtp_transfer_param::sio, osmo_mtp_transfer_param::sls, and m3ua_data_hdr::sls.
Referenced by ipa_rx_msg_sccp(), m3ua_rx_xfer(), and m3ua_to_xfer_ind().
struct xua_msg* m3ua_encode_notify (const struct osmo_xlm_prim_notify * npar)
References osmo_xlm_prim_notify::asp_id, xua_msg::hdr, osmo_xlm_prim_notify::info_string, M3UA_IEI_ASP_ID, M3UA_IEI_INFO_STRING, M3UA_IEI_ROUTE_CTX, M3UA_IEI_STATUS, M3UA_MGMT_NTFY, M3UA_MSGC_MGMT, M3UA_NOTIFY, NOTIFY_PAR_P_ASP_ID, NOTIFY_PAR_P_ROUTE_CTX, osmo_xlm_prim_notify::presence, osmo_xlm_prim_notify::route_ctx, osmo_xlm_prim_notify::status_info, osmo_xlm_prim_notify::status_type, XUA_HDR, xua_msg_add_data(), xua_msg_add_u32(), and xua_msg_alloc().
Referenced by encode_notify().
static struct xua_msg* m3ua_gen_error (uint32_t err_code) [static]
References xua_msg::hdr, M3UA_IEI_ERR_CODE, M3UA_MGMT_ERR, M3UA_MSGC_MGMT, M3UA_VERSION, xua_common_hdr::version, XUA_HDR, xua_msg_add_u32(), and xua_msg_alloc().
Referenced by m3ua_gen_error_msg().
static struct xua_msg* m3ua_gen_error_msg (uint32_t err_code, struct msgb * msg) [static]
References m3ua_gen_error(), M3UA_IEI_DIAG_INFO, and xua_msg_add_data().
Referenced by m3ua_rx_msg().
struct msgb* m3ua_msgb_alloc (const char * name)
References M3UA_MSG_HEADROOM, and M3UA_MSG_SIZE.
Referenced by m3ua_rx_rkm_dereg_req(), m3ua_rx_rkm_reg_req(), m3ua_to_xfer_ind(), xua_cli_read_cb(), xua_rkm_send_dereg_req(), xua_rkm_send_reg_req(), and xua_srv_conn_cb().
static int m3ua_rx_asp (struct osmo_ss7_asp * asp, struct xua_msg * xua) [static]
References xua_msg_event_map::event, osmo_ss7_asp::fi, M3UA_ERR_UNEXPECTED_MSG, M3UA_ERR_UNSUPP_MSG_TYPE, and xua_msg_event_map().
Referenced by m3ua_rx_msg().
static int m3ua_rx_mgmt (struct osmo_ss7_asp * asp, struct xua_msg * xua) [static]
References xua_msg::hdr, M3UA_ERR_UNSUPP_MSG_TYPE, M3UA_MGMT_ERR, M3UA_MGMT_NTFY, m3ua_rx_mgmt_err(), m3ua_rx_mgmt_ntfy(), and xua_common_hdr::msg_type.
Referenced by m3ua_rx_msg().
static int m3ua_rx_mgmt_err (struct osmo_ss7_asp * asp, struct xua_msg * xua) [static]
References osmo_xlm_prim_error::code, osmo_xlm_prim::error, LOGPASP, m3ua_err_names, M3UA_IEI_ERR_CODE, OSMO_XLM_PRIM_M_ERROR, osmo_xlm_prim::u, xua_asp_send_xlm_prim(), xua_msg_dump(), xua_msg_get_u32(), and xua_xlm_prim_alloc().
Referenced by m3ua_rx_mgmt().
static int m3ua_rx_mgmt_ntfy (struct osmo_ss7_asp * asp, struct xua_msg * xua) [static]
References osmo_xlm_prim_notify::info_string, LOGPASP, m3ua_decode_notify(), M3UA_NOTIFY_T_OTHER, M3UA_NOTIFY_T_STATCHG, m3ua_ntfy_other_names, m3ua_ntfy_stchg_names, m3ua_ntfy_type_names, osmo_xlm_prim::notify, OSMO_XLM_PRIM_M_NOTIFY, osmo_xlm_prim_notify::status_info, osmo_xlm_prim_notify::status_type, osmo_xlm_prim::u, xua_asp_send_xlm_prim(), and xua_xlm_prim_alloc().
Referenced by m3ua_rx_mgmt().
int m3ua_rx_msg (struct osmo_ss7_asp * asp, struct msgb * msg)
process M3UA message received from socket
Parameters
in asp Application Server Process receiving msg
in msg received message buffer
Returns
0 on success; negative on error
References osmo_ss7_asp::cfg, xua_common_hdr::data, xua_msg::hdr, LOGPASP, M3UA_ERR_INVAL_STREAM_ID, M3UA_ERR_INVALID_VERSION, M3UA_ERR_MISSING_PARAM, M3UA_ERR_PARAM_FIELD_ERR, M3UA_ERR_UNSUPP_MSG_CLASS, m3ua_gen_error_msg(), M3UA_MSGC_ASPSM, M3UA_MSGC_ASPTM, M3UA_MSGC_MGMT, M3UA_MSGC_RKM, M3UA_MSGC_SNM, M3UA_MSGC_XFER, m3ua_rx_asp(), m3ua_rx_mgmt(), m3ua_rx_rkm(), m3ua_rx_xfer(), m3ua_tx_xua_asp(), M3UA_VERSION, xua_common_hdr::msg_class, OSMO_SS7_ASP_PROT_M3UA, osmo_ss7_asp::proto, xua_common_hdr::version, xua_dialect_check_all_mand_ies(), xua_from_msg(), xua_hdr_dump(), and xua_msg_free().
Referenced by xua_cli_read_cb(), and xua_srv_conn_cb().
static int m3ua_rx_xfer (struct osmo_ss7_asp * asp, struct xua_msg * xua) [static]
References data_hdr_from_m3ua(), osmo_mtp_transfer_param::dpc, xua_msg::hdr, osmo_ss7_asp::inst, LOGPASP, m3ua_dh_to_xfer_param(), M3UA_ERR_INVAL_ROUT_CTX, M3UA_ERR_NO_CONFGD_AS_FOR_ASP, M3UA_ERR_UNSUPP_MSG_TYPE, m3ua_hmdc_rx_from_l2(), M3UA_IEI_ROUTE_CTX, M3UA_XFER_DATA, m3ua_xfer_msgt_names, xua_common_hdr::msg_type, xua_msg::mtp, osmo_mtp_transfer_param::opc, osmo_ss7_as_find_by_rctx(), osmo_ss7_as_has_asp(), osmo_ss7_pointcode_print(), osmo_ss7_pointcode_print2(), xua_msg_free_tag(), and xua_msg_get_u32().
Referenced by m3ua_rx_msg().
static struct msgb* m3ua_to_msg (struct xua_msg * xua) [static]
References xua_msg::hdr, M3UA_MSGC_XFER, M3UA_PPID, M3UA_VERSION, xua_common_hdr::msg_class, and xua_to_msg().
Referenced by m3ua_tx_xua_as(), and m3ua_tx_xua_asp().
int m3ua_tx_xua_as (struct osmo_ss7_as * as, struct xua_msg * xua)
Send a given xUA message via a given M3UA Application Server.
Parameters
in as Application Server through which to send xua
in xua xUA message to be sent
Returns
0 on success; negative on error
References osmo_ss7_as::cfg, osmo_ss7_routing_key::context, osmo_ss7_as::fi, M3UA_IEI_ROUTE_CTX, m3ua_to_msg(), OSMO_SS7_ASP_PROT_M3UA, osmo_ss7_as::proto, osmo_ss7_as::routing_key, XUA_AS_E_TRANSFER_REQ, and xua_msg_add_u32().
Referenced by hmrt_message_for_routing().
static int m3ua_tx_xua_asp (struct osmo_ss7_asp * asp, struct xua_msg * xua) [static]
References osmo_ss7_asp::cfg, m3ua_to_msg(), OSMO_SS7_ASP_PROT_M3UA, osmo_ss7_asp_send(), and osmo_ss7_asp::proto.
Referenced by m3ua_rx_msg().
struct xua_msg* m3ua_xfer_from_data (const struct m3ua_data_hdr * data_hdr, const uint8_t * data, unsigned int data_len)
References xua_msg_part::dat, xua_msg_part::entry, xua_msg::hdr, xua_msg::headers, xua_msg_part::len, M3UA_IEI_PROT_DATA, M3UA_MSGC_XFER, M3UA_XFER_DATA, xua_msg_part::tag, XUA_HDR, and xua_msg_alloc().
Referenced by ipa_rx_msg_sccp(), and mtp_prim_to_m3ua().
void mtp_xfer_param_to_m3ua_dh (struct m3ua_data_hdr * mdh, const struct osmo_mtp_transfer_param * param)
References osmo_mtp_transfer_param::dpc, m3ua_data_hdr::dpc, m3ua_data_hdr::mp, m3ua_data_hdr::ni, osmo_mtp_transfer_param::opc, m3ua_data_hdr::opc, m3ua_data_hdr::si, osmo_mtp_transfer_param::sio, osmo_mtp_transfer_param::sls, and m3ua_data_hdr::sls.
Referenced by mtp_prim_to_m3ua().
Variable Documentation
const uint16_t data_mand_ies[] [static]
Initial value:
= {
        M3UA_IEI_PROT_DATA, 0
}
const uint16_t daud_mand_ies[] [static]
Initial value:
= {
        M3UA_IEI_AFFECTED_PC, 0
}
const uint16_t dava_mand_ies[] [static]
Initial value:
= {
        M3UA_IEI_AFFECTED_PC, 0
}
const uint16_t dereg_req_ies[] [static]
Initial value:
= {
        M3UA_IEI_ROUTE_CTX, 0
}
const uint16_t dereg_rsp_ies[] [static]
Initial value:
= {
        M3UA_IEI_DEREG_RESULT, 0
}
const uint16_t drst_mand_ies[] [static]
Initial value:
= {
        M3UA_IEI_AFFECTED_PC, 0
}
const uint16_t duna_mand_ies[] [static]
Initial value:
= {
        M3UA_IEI_AFFECTED_PC, 0
}
const uint16_t dupu_mand_ies[] [static]
Initial value:
= {
        M3UA_IEI_AFFECTED_PC, M3UA_IEI_USER_CAUSE, 0
}
const uint16_t err_req_ies[] [static]
Initial value:
= {
        M3UA_IEI_ERR_CODE, 0
}
const struct value_string m3ua_aspsm_msgt_names[] [static]
Initial value:
= {
        { M3UA_ASPSM_UP, "UP" },
        { M3UA_ASPSM_DOWN, "DOWN" },
        { M3UA_ASPSM_BEAT, "BEAT" },
        { M3UA_ASPSM_UP_ACK, "UP-ACK" },
        { M3UA_ASPSM_DOWN_ACK, "DOWN-ACK" },
        { M3UA_ASPSM_BEAT_ACK, "BEAT-ACK" },
        { 0, NULL }
}
const struct value_string m3ua_asptm_msgt_names[]
Initial value:
= {
        { M3UA_ASPTM_ACTIVE, "ACTIVE" },
        { M3UA_ASPTM_INACTIVE, "INACTIVE" },
        { M3UA_ASPTM_ACTIVE_ACK,"ACTIVE-ACK" },
        { M3UA_ASPTM_INACTIVE_ACK, "INACTIVE-ACK" },
        { 0, NULL }
}
const struct xua_msg_event_map m3ua_aspxm_map[] [static]
Initial value:
= {
        { M3UA_MSGC_ASPSM, M3UA_ASPSM_UP, XUA_ASP_E_ASPSM_ASPUP },
        { M3UA_MSGC_ASPSM, M3UA_ASPSM_DOWN, XUA_ASP_E_ASPSM_ASPDN },
        { M3UA_MSGC_ASPSM, M3UA_ASPSM_BEAT, XUA_ASP_E_ASPSM_BEAT },
        { M3UA_MSGC_ASPSM, M3UA_ASPSM_UP_ACK, XUA_ASP_E_ASPSM_ASPUP_ACK },
        { M3UA_MSGC_ASPSM, M3UA_ASPSM_DOWN_ACK, XUA_ASP_E_ASPSM_ASPDN_ACK },
        { M3UA_MSGC_ASPSM, M3UA_ASPSM_BEAT_ACK, XUA_ASP_E_ASPSM_BEAT_ACK },
        { M3UA_MSGC_ASPTM, M3UA_ASPTM_ACTIVE, XUA_ASP_E_ASPTM_ASPAC },
        { M3UA_MSGC_ASPTM, M3UA_ASPTM_INACTIVE, XUA_ASP_E_ASPTM_ASPIA },
        { M3UA_MSGC_ASPTM, M3UA_ASPTM_ACTIVE_ACK, XUA_ASP_E_ASPTM_ASPAC_ACK },
        { M3UA_MSGC_ASPTM, M3UA_ASPTM_INACTIVE_ACK, XUA_ASP_E_ASPTM_ASPIA_ACK },
}
const struct value_string m3ua_err_names[]
Initial value:
= {
        { M3UA_ERR_INVALID_VERSION, "Invalid Version" },
        { M3UA_ERR_UNSUPP_MSG_CLASS, "Unsupported Message Class" },
        { M3UA_ERR_UNSUPP_MSG_TYPE, "Unsupported Message Type" },
        { M3UA_ERR_UNSUPP_TRAF_MOD_TYP, "Unsupported Traffic Mode Type" },
        { M3UA_ERR_UNEXPECTED_MSG, "Unexpected Message" },
        { M3UA_ERR_PROTOCOL_ERR, "Protocol Error" },
        { M3UA_ERR_INVAL_STREAM_ID, "Invalid Stream Identifier" },
        { M3UA_ERR_REFUSED_MGMT_BLOCKING, "Refused - Management Blocking" },
        { M3UA_ERR_ASP_ID_REQD, "ASP Identifier Required" },
        { M3UA_ERR_INVAL_ASP_ID, "Invalid ASP Identifier" },
        { M3UA_ERR_INVAL_PARAM_VAL, "Invalid Parameter Value" },
        { M3UA_ERR_PARAM_FIELD_ERR, "Parameter Field Error" },
        { M3UA_ERR_UNEXP_PARAM, "Unexpected Parameter" },
        { M3UA_ERR_DEST_STATUS_UNKN, "Destination Status Unknown" },
        { M3UA_ERR_INVAL_NET_APPEAR, "Invalid Network Appearance" },
        { M3UA_ERR_MISSING_PARAM, "Missing Parameter" },
        { M3UA_ERR_INVAL_ROUT_CTX, "Invalid Routing Context" },
        { M3UA_ERR_NO_CONFGD_AS_FOR_ASP,"No Configured AS for ASP" },
        { SUA_ERR_SUBSYS_STATUS_UNKN, "Subsystem Status Unknown" },
        { SUA_ERR_INVAL_LOADSH_LEVEL, "Invalid loadsharing level" },
        { 0, NULL }
}
Referenced by m3ua_rx_mgmt_err(), and sua_rx_mgmt_err().
const struct value_string m3ua_iei_names[] [static]
Initial value:
= {
        { M3UA_IEI_INFO_STRING, "INFO String" },
        { M3UA_IEI_ROUTE_CTX, "Routing Context" },
        { M3UA_IEI_DIAG_INFO, "Diagnostic Info" },
        { M3UA_IEI_HEARDBT_DATA, "Heartbeat Data" },
        { M3UA_IEI_TRAF_MODE_TYP, "Traffic Mode Type" },
        { M3UA_IEI_ERR_CODE, "Error Code" },
        { M3UA_IEI_STATUS, "Status" },
        { M3UA_IEI_ASP_ID, "ASP Identifier" },
        { M3UA_IEI_AFFECTED_PC, "Affected Point Code" },
        { M3UA_IEI_CORR_ID, "Correlation Id" },
        { M3UA_IEI_NET_APPEAR, "Network Appearance" },
        { M3UA_IEI_USER_CAUSE, "User/Cause" },
        { M3UA_IEI_CONG_IND, "Congestion Indication" },
        { M3UA_IEI_CONC_DEST, "Concerned Destination" },
        { M3UA_IEI_ROUT_KEY, "Routing Key" },
        { M3UA_IEI_REG_RESULT, "Registration Result" },
        { M3UA_IEI_DEREG_RESULT, "De-Registration Result" },
        { M3UA_IEI_LOC_RKEY_ID, "Local Routing-Key Identifier" },
        { M3UA_IEI_DEST_PC, "Destination Point Code" },
        { M3UA_IEI_SVC_IND, "Service Indicators" },
        { M3UA_IEI_ORIG_PC, "Originating Point Code List" },
        { M3UA_IEI_PROT_DATA, "Protocol Data" },
        { M3UA_IEI_REG_STATUS, "Registration Status" },
        { M3UA_IEI_DEREG_STATUS, "De-Registration Status" },
        { 0, NULL }
}
const struct value_string m3ua_mgmt_msgt_names[] [static]
Initial value:
= {
        { M3UA_MGMT_ERR, "ERROR" },
        { M3UA_MGMT_NTFY, "NOTIFY" },
        { 0, NULL }
}
const struct xua_msg_class m3ua_msg_class_aspsm
Initial value:
= {
        .name = "ASPSM",
        .msgt_names = m3ua_aspsm_msgt_names,
}
const struct xua_msg_class m3ua_msg_class_asptm
Initial value:
= {
        .name = "ASPTM",
        .msgt_names = m3ua_asptm_msgt_names,
        .iei_names = m3ua_iei_names,
}
const struct xua_msg_class m3ua_msg_class_mgmt
Initial value:
= {
        .name = "MGMT",
        .msgt_names = m3ua_mgmt_msgt_names,
        .iei_names = m3ua_iei_names,
        .mand_ies = {
                MAND_IES(M3UA_MGMT_ERR, err_req_ies),
                MAND_IES(M3UA_MGMT_NTFY, ntfy_req_ies),
        },
}
const struct xua_msg_class m3ua_msg_class_rkm
Initial value:
= {
        .name = "RKM",
        .msgt_names = m3ua_rkm_msgt_names,
        .iei_names = m3ua_iei_names,
        .mand_ies = {
                MAND_IES(M3UA_RKM_REG_REQ, reg_req_ies),
                MAND_IES(M3UA_RKM_REG_RSP, reg_rsp_ies),
                MAND_IES(M3UA_RKM_DEREG_REQ, dereg_req_ies),
                MAND_IES(M3UA_RKM_DEREG_RSP, dereg_rsp_ies),
        },
}
const struct xua_msg_class m3ua_msg_class_snm
Initial value:
= {
        .name = "SNM",
        .msgt_names = m3ua_snm_msgt_names,
        .mand_ies = {
                MAND_IES(M3UA_SNM_DUNA, duna_mand_ies),
                MAND_IES(M3UA_SNM_DAVA, dava_mand_ies),
                MAND_IES(M3UA_SNM_DAUD, daud_mand_ies),
                MAND_IES(M3UA_SNM_SCON, scon_mand_ies),
                MAND_IES(M3UA_SNM_DUPU, dupu_mand_ies),
                MAND_IES(M3UA_SNM_DRST, drst_mand_ies),
        },
}
const struct value_string m3ua_ntfy_other_names[]
Initial value:
= {
        { M3UA_NOTIFY_I_OT_INS_RES, "Insufficient ASP Resouces active in AS" },
        { M3UA_NOTIFY_I_OT_ALT_ASP_ACT, "Alternative ASP Active" },
        { M3UA_NOTIFY_I_OT_ASP_FAILURE, "ASP Failure" },
        { 0, NULL }
}
Referenced by m3ua_rx_mgmt_ntfy(), and sua_rx_mgmt_ntfy().
const struct value_string m3ua_ntfy_stchg_names[]
Initial value:
= {
        { M3UA_NOTIFY_I_RESERVED, "Reserved" },
        { M3UA_NOTIFY_I_AS_INACT, "AS Inactive" },
        { M3UA_NOTIFY_I_AS_ACT, "AS Active" },
        { M3UA_NOTIFY_I_AS_PEND, "AS Pending" },
        { 0, NULL }
}
Referenced by m3ua_rx_mgmt_ntfy(), and sua_rx_mgmt_ntfy().
const struct value_string m3ua_ntfy_type_names[]
Initial value:
= {
        { M3UA_NOTIFY_T_STATCHG, "State Change" },
        { M3UA_NOTIFY_T_OTHER, "Other" },
        { 0, NULL }
}
Referenced by m3ua_rx_mgmt_ntfy(), and sua_rx_mgmt_ntfy().
const struct value_string m3ua_rkm_msgt_names[] [static]
Initial value:
= {
        { M3UA_RKM_REG_REQ, "REG-REQ" },
        { M3UA_RKM_REG_RSP, "REG-RESP" },
        { M3UA_RKM_DEREG_REQ, "DEREG-REQ" },
        { M3UA_RKM_DEREG_RSP, "DEREG-RESP" },
        { 0, NULL }
}
const struct value_string m3ua_snm_msgt_names[] [static]
Initial value:
= {
        { M3UA_SNM_DUNA, "DUNA" },
        { M3UA_SNM_DAVA, "DAVA" },
        { M3UA_SNM_DAUD, "DAUD" },
        { M3UA_SNM_SCON, "SCON" },
        { M3UA_SNM_DUPU, "DUPU" },
        { M3UA_SNM_DRST, "DRST" },
        { 0, NULL }
}
const struct value_string m3ua_xfer_msgt_names[] [static]
Initial value:
= {
        { M3UA_XFER_DATA, "DATA" },
        { 0, NULL }
}
Referenced by m3ua_rx_xfer().
const struct xua_msg_class msg_class_xfer [static]
Initial value:
= {
        .name = "XFER",
        .msgt_names = m3ua_xfer_msgt_names,
        .mand_ies = {
                MAND_IES(M3UA_XFER_DATA, data_mand_ies),
        },
}
const uint16_t ntfy_req_ies[] [static]
Initial value:
= {
        M3UA_IEI_STATUS, 0
}
const uint16_t reg_req_ies[] [static]
Initial value:
= {
        M3UA_IEI_ROUT_KEY, 0
}
const uint16_t reg_rsp_ies[] [static]
Initial value:
= {
        M3UA_IEI_REG_RESULT, 0
}
const uint16_t scon_mand_ies[] [static]
Initial value:
= {
        M3UA_IEI_AFFECTED_PC, 0
}
const struct xua_dialect xua_dialect_m3ua
Initial value:
= {
        .name = "M3UA",
        .ppid = M3UA_PPID,
        .port = M3UA_PORT,
        .log_subsys = DLM3UA,
        .class = {
                [M3UA_MSGC_MGMT] = &m3ua_msg_class_mgmt,
                [M3UA_MSGC_XFER] = &msg_class_xfer,
                [M3UA_MSGC_SNM] = &m3ua_msg_class_snm,
                [M3UA_MSGC_ASPSM] = &m3ua_msg_class_aspsm,
                [M3UA_MSGC_ASPTM] = &m3ua_msg_class_asptm,
                [M3UA_MSGC_RKM] = &m3ua_msg_class_rkm,
        },
}